export const CREATE_COUNTRY = "COUNTRY/CREATE_COUNTRY";
export const FETCH_COUNTRIES = "COUNTRY/FETCH_COUNTRIES";

//Saga
 export const REQUEST_COUNTRIES = "COUNTRY/REQUEST_COUNTRIES";

 //Alert
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";

//Loader
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";